
import * as d from './components';

export const DIRECTIVES = [
  d.AndAccordion,
  d.AndAccordionContent,
  d.AndAccordionItem,
  d.AndAccordionTrigger,
  d.AndAlert,
  d.AndBadge,
  d.AndBreadcrumb,
  d.AndBreadcrumbItem,
  d.AndButton,
  d.AndCard,
  d.AndCardContent,
  d.AndCardDescription,
  d.AndCardFooter,
  d.AndCardHeader,
  d.AndCardTitle,
  d.AndCarousel,
  d.AndCarouselItem,
  d.AndContextMenu,
  d.AndDrawer,
  d.AndDropdown,
  d.AndIcon,
  d.AndInput,
  d.AndMenuItem,
  d.AndMenuList,
  d.AndModal,
  d.AndNavbar,
  d.AndPagination,
  d.AndSelect,
  d.AndSidebar,
  d.AndTabs,
  d.AndTabsContent,
  d.AndTabsList,
  d.AndTabsTrigger,
  d.AndToast,
  d.AndTooltip
];
