/**
 * And Button - Vanilla Web Component
 * Build-time: Uses CVA + Tailwind
 * Runtime: Zero dependencies
 */

import type { ButtonReturn } from '@andersseen/headless-components';
import { createButton } from '@andersseen/headless-components';
import { Component, Event, Prop, Watch } from '../../decorators';

// 🎯 BUILD TIME: CVA generates static classes
// This code runs at build time to generate CSS

@Component({
  tag: 'and-button',
  shadow: true,
  // Styles are extracted at build time - no Tailwind runtime!
  styles: `
    :host {
      display: inline-flex;
    }

    button {
      position: relative;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: var(--spacing-2);
      font-family: var(--font-sans);
      font-weight: 500;
      line-height: 1.5;
      border: none;
      border-radius: var(--radius-md);
      cursor: pointer;
      transition: all var(--transition-fast);
      white-space: nowrap;
      outline: none;
    }

    button:focus-visible {
      outline: 2px solid var(--color-ring);
      outline-offset: 2px;
    }

    button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    /* Variants - generated by CVA at build time */
    button[data-variant='default'] {
      background-color: var(--color-primary);
      color: var(--color-primary-foreground);
    }

    button[data-variant='default']:hover:not(:disabled) {
      background-color: color-mix(in srgb, var(--color-primary) 90%, black);
    }

    button[data-variant='destructive'] {
      background-color: var(--color-destructive);
      color: var(--color-destructive-foreground);
    }

    button[data-variant='destructive']:hover:not(:disabled) {
      background-color: color-mix(in srgb, var(--color-destructive) 90%, black);
    }

    button[data-variant='outline'] {
      background-color: transparent;
      border: 1px solid var(--color-border);
      color: var(--color-foreground);
    }

    button[data-variant='outline']:hover:not(:disabled) {
      background-color: var(--color-accent);
    }

    button[data-variant='secondary'] {
      background-color: var(--color-secondary);
      color: var(--color-secondary-foreground);
    }

    button[data-variant='secondary']:hover:not(:disabled) {
      background-color: color-mix(in srgb, var(--color-secondary) 90%, black);
    }

    button[data-variant='ghost'] {
      background-color: transparent;
      color: var(--color-foreground);
    }

    button[data-variant='ghost']:hover:not(:disabled) {
      background-color: var(--color-accent);
    }

    button[data-variant='link'] {
      background-color: transparent;
      color: var(--color-primary);
      text-decoration: underline;
      underline-offset: 4px;
    }

    button[data-variant='link']:hover:not(:disabled) {
      text-decoration: none;
    }

    /* Sizes */
    button[data-size='default'] {
      height: 2.5rem;
      padding: 0 var(--spacing-4);
      font-size: 0.875rem;
    }

    button[data-size='sm'] {
      height: 2.25rem;
      padding: 0 var(--spacing-3);
      font-size: 0.875rem;
      border-radius: var(--radius-md);
    }

    button[data-size='lg'] {
      height: 2.75rem;
      padding: 0 var(--spacing-6);
      font-size: 1rem;
      border-radius: var(--radius-md);
    }

    button[data-size='icon'] {
      height: 2.5rem;
      width: 2.5rem;
      padding: 0;
    }

    /* Loading state */
    button[data-loading='true'] {
      cursor: wait;
    }

    button[data-loading='true'] .content {
      opacity: 0;
    }

    .spinner {
      position: absolute;
      width: 1rem;
      height: 1rem;
      border: 2px solid currentColor;
      border-right-color: transparent;
      border-radius: 50%;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      to {
        transform: rotate(360deg);
      }
    }
  `,
})
export class AndButton extends HTMLElement {
  // Static observedAttributes for attributeChangedCallback
  static observedAttributes = ['variant', 'size', 'disabled', 'loading'];

  // Reactive properties
  @Prop({ reflect: true })
  variant: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link' = 'default';

  @Prop({ reflect: true })
  size: 'default' | 'sm' | 'lg' | 'icon' = 'default';

  @Prop({ reflect: true, type: Boolean })
  disabled: boolean = false;

  @Prop({ reflect: true, type: Boolean })
  loading: boolean = false;

  // Internal state
  private buttonLogic: ButtonReturn | null = null;
  private buttonElement: HTMLButtonElement | null = null;

  // Custom events
  @Event()
  andButtonClick!: (detail?: any) => void;

  // Lifecycle: connected to DOM
  connectedCallback() {
    this.render();
    this.setupButtonLogic();
  }

  // Lifecycle: disconnected from DOM
  disconnectedCallback() {
    // Cleanup if needed
    this.buttonLogic = null;
  }

  // Lifecycle: attribute changed
  attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null) {
    if (oldValue === newValue) return;

    // Update property from attribute
    const propName = name.replace(/-([a-z])/g, g => g[1].toUpperCase());
    (this as any)[propName] = newValue;

    // Re-render
    this.updateButton();
  }

  @Watch('variant')
  onVariantChange() {
    this.updateButton();
  }

  @Watch('size')
  onSizeChange() {
    this.updateButton();
  }

  @Watch('disabled')
  onDisabledChange() {
    this.updateButton();
    if (this.buttonLogic) {
      this.buttonLogic.actions.setDisabled(this.disabled);
    }
  }

  @Watch('loading')
  onLoadingChange() {
    this.updateButton();
    if (this.buttonLogic) {
      this.buttonLogic.actions.setLoading(this.loading);
    }
  }

  private setupButtonLogic() {
    if (!this.buttonElement) return;

    this.buttonLogic = createButton({
      disabled: this.disabled,
      loading: this.loading,
      onClick: event => {
        this.andButtonClick({ originalEvent: event });
      },
    });

    // Apply accessibility props
    const props = this.buttonLogic.getButtonProps();
    Object.entries(props).forEach(([key, value]) => {
      if (key.startsWith('aria-')) {
        this.buttonElement?.setAttribute(key, String(value));
      }
    });

    // Setup click handler
    this.buttonElement.addEventListener('click', e => {
      if (this.disabled || this.loading) {
        e.preventDefault();
        e.stopPropagation();
        return;
      }
      this.buttonLogic?.actions.click();
    });
  }

  private render() {
    if (!this.shadowRoot) {
      this.attachShadow({ mode: 'open', delegatesFocus: true });
    }

    // Get metadata for styles
    const metadata = (this.constructor as any).metadata;

    this.shadowRoot!.innerHTML = `
      <style>${metadata?.styles || ''}</style>
      <button
        part="base"
        data-variant="${this.variant}"
        data-size="${this.size}"
        data-loading="${this.loading}"
        ?disabled="${this.disabled}"
        type="button"
      >
        <span class="content">
          <slot></slot>
        </span>
        ${this.loading ? '<span class="spinner" aria-hidden="true"></span>' : ''}
      </button>
    `;

    this.buttonElement = this.shadowRoot!.querySelector('button');
  }

  private updateButton() {
    if (!this.buttonElement) return;

    this.buttonElement.setAttribute('data-variant', this.variant);
    this.buttonElement.setAttribute('data-size', this.size);
    this.buttonElement.setAttribute('data-loading', String(this.loading));

    if (this.disabled) {
      this.buttonElement.setAttribute('disabled', '');
    } else {
      this.buttonElement.removeAttribute('disabled');
    }

    // Update spinner visibility
    const spinner = this.buttonElement.querySelector('.spinner');
    if (this.loading && !spinner) {
      this.buttonElement.insertAdjacentHTML('beforeend', '<span class="spinner" aria-hidden="true"></span>');
    } else if (!this.loading && spinner) {
      spinner.remove();
    }
  }
}

// Auto-register if not already registered
if (!customElements.get('and-button')) {
  customElements.define('and-button', AndButton);
}
