import { ALL_ICONS } from './icons';

/**
 * The exact `<svg>` shell `<and-icon>` (`packages/web-components/src/components/and-icon/and-icon.tsx`)
 * wraps every registered icon's inner markup in, so the CSS-mask render and
 * the Web Component render stay pixel-identical.
 */
const wrapSvg = (innerMarkup: string): string =>
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
  `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${innerMarkup}</svg>`;

/**
 * Base64-encoded `data:image/svg+xml` URI. Chosen over percent-encoding:
 * base64 round-trips any character in the source markup without a custom
 * escaping table to get wrong.
 */
const toDataUri = (svg: string): string => `data:image/svg+xml;base64,${Buffer.from(svg, 'utf-8').toString('base64')}`;

const BASE_RULE = `[and-icon] {
  display: inline-block;
  width: 1em;
  height: 1em;
  background-color: currentColor;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-position: center;
  mask-position: center;
  -webkit-mask-size: contain;
  mask-size: contain;
}`;

const BANNER = `/**
 * AUTO-GENERATED by packages/icon-library/scripts/build-icons-css.mjs — do not edit by hand.
 * Source of truth: packages/icon-library/src/icons.ts (ALL_ICONS).
 * Regenerate with: pnpm -C packages/icon-library build
 */`;

/**
 * Generates the CSS mask-icon stylesheet consumed by \`and-icon="<name>"\`
 * (see docs). Reads from the same \`ALL_ICONS\` map \`<and-icon>\` reads from —
 * there is no second, hand-maintained copy of the icon set.
 *
 * Defaults to the full catalog; pass a subset map to generate a smaller
 * stylesheet for consumers who only need a handful of icons:
 *
 * ```ts
 * import { generateIconsCss } from '@andersseen/icon/generate-css';
 * import { HOME, SEARCH, CLOSE } from '@andersseen/icon';
 * import { writeFileSync } from 'node:fs';
 *
 * writeFileSync('subset-icons.css', generateIconsCss({ home: HOME, search: SEARCH, close: CLOSE }));
 * ```
 *
 * Node-only (uses `Buffer`) — not meant to run in a browser bundle.
 */
export const generateIconsCss = (icons: Record<string, string> = ALL_ICONS): string => {
  const names = Object.keys(icons).sort();

  const perIconRules = names.map(name => {
    const dataUri = toDataUri(wrapSvg(icons[name]));
    return `[and-icon='${name}'] {
  -webkit-mask-image: url('${dataUri}');
  mask-image: url('${dataUri}');
}`;
  });

  return `${[BANNER, BASE_RULE, ...perIconRules].join('\n\n')}\n`;
};
