#!/usr/bin/env node
/**
 * Generates `src/catalog-generated.ts` from the Stencil-produced
 * `custom-elements.json` (CEM 2.1.0) of `@andersseen/web-components`.
 *
 * The MCP server serves this catalog, so it stays in sync with the real
 * components automatically — never hand-edit `catalog-generated.ts`.
 *
 *   node scripts/generate-catalog.mjs           # write the file
 *   node scripts/generate-catalog.mjs --check    # fail if it would change
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const CEM_PATH = resolve(here, '../../web-components/custom-elements.json');
const OUT_PATH = resolve(here, '../src/catalog-generated.ts');
const CHECK = process.argv.includes('--check');

// `custom-elements.json` is a build artifact of @andersseen/web-components and
// is not committed. `catalog-generated.ts` IS committed and is what ships in
// the package, so when the CEM is absent (fresh clone / CI before Stencil is
// built) we fall back to the checked-in catalog instead of failing the build.
if (!existsSync(CEM_PATH)) {
  const msg = 'custom-elements.json not found (build @andersseen/web-components to refresh the catalog).';
  if (existsSync(OUT_PATH)) {
    console.warn(`⚠ ${msg} Using the committed src/catalog-generated.ts.`);
    process.exit(0);
  }
  console.error(`✖ ${msg} No committed catalog to fall back to.`);
  process.exit(CHECK ? 0 : 1);
}

function clean(text) {
  return typeof text === 'string' ? text.replace(/\s+/g, ' ').trim() : undefined;
}

function readDeclarations() {
  const cem = JSON.parse(readFileSync(CEM_PATH, 'utf8'));
  const decls = [];
  for (const mod of cem.modules ?? []) {
    for (const decl of mod.declarations ?? []) {
      if (decl.customElement && decl.tagName) decls.push(decl);
    }
  }
  return decls.sort((a, b) => a.tagName.localeCompare(b.tagName));
}

function toComponent(decl, allTags) {
  const attributes = (decl.attributes ?? []).map(a => ({
    name: a.name,
    field: a.fieldName ?? a.name,
    type: clean(a.type?.text) ?? 'string',
    default: clean(a.default),
    description: clean(a.description),
  }));

  const events = (decl.events ?? []).map(e => ({
    name: e.name,
    description: clean(e.description),
    type: clean(e.type?.text),
  }));

  const methods = (decl.members ?? [])
    .filter(m => m.kind === 'method' && m.privacy !== 'private' && !m.static)
    .map(m => ({ name: m.name, description: clean(m.description) }));

  const slots = (decl.slots ?? []).map(s => ({
    name: s.name || 'default',
    description: clean(s.description),
  }));

  const cssParts = (decl.cssParts ?? []).map(p => ({
    name: p.name,
    description: clean(p.description),
  }));

  // Longest other tag that is a strict prefix → structural parent
  // (e.g. `and-accordion-item` → `and-accordion`).
  let parent;
  for (const other of allTags) {
    if (other !== decl.tagName && decl.tagName.startsWith(`${other}-`)) {
      if (!parent || other.length > parent.length) parent = other;
    }
  }

  return {
    tag: decl.tagName,
    name: decl.name,
    description: clean(decl.description) ?? '',
    ...(parent ? { parent } : {}),
    attributes,
    events,
    methods,
    slots,
    cssParts,
  };
}

function build() {
  const decls = readDeclarations();
  const allTags = decls.map(d => d.tagName);
  const components = decls.map(d => toComponent(d, allTags));

  const banner =
    '// AUTO-GENERATED by scripts/generate-catalog.mjs from\n' +
    '// @andersseen/web-components/custom-elements.json. Do not edit by hand;\n' +
    '// run `pnpm --filter @andersseen/mcp generate` after changing components.\n';

  return (
    `${banner}\n` +
    `import type { Component } from './types';\n\n` +
    `export const CATALOG_VERSION = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n\n` +
    `export const catalog: Component[] = ${JSON.stringify(components, null, 2)};\n`
  );
}

const output = build();

if (CHECK) {
  let current = '';
  try {
    current = readFileSync(OUT_PATH, 'utf8');
  } catch {
    /* missing file counts as out of date */
  }
  if (current !== output) {
    console.error('✖ catalog-generated.ts is out of date. Run: pnpm --filter @andersseen/mcp generate');
    process.exit(1);
  }
  console.log('✓ catalog-generated.ts is in sync with custom-elements.json');
} else {
  writeFileSync(OUT_PATH, output);
  const count = (output.match(/"tag":/g) ?? []).length;
  console.log(`✓ Wrote ${count} components to src/catalog-generated.ts`);
}
