// AUTO-GENERATED by scripts/generate-catalog.mjs from
// @andersseen/web-components/custom-elements.json. Do not edit by hand;
// run `pnpm --filter @andersseen/mcp generate` after changing components.

import type { Component } from './types';

export const CATALOG_VERSION = "2026-07-21";

export const catalog: Component[] = [
  {
    "tag": "and-accordion",
    "name": "AndAccordion",
    "description": "Accordion container component using headless logic.",
    "attributes": [
      {
        "name": "allow-multiple",
        "field": "allowMultiple",
        "type": "boolean",
        "default": "false",
        "description": "Allow multiple items to be expanded simultaneously."
      },
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Whether the accordion is disabled."
      },
      {
        "name": "orientation",
        "field": "orientation",
        "type": "\"horizontal\" | \"vertical\"",
        "default": "'vertical'",
        "description": "Orientation of the accordion."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-accordion-content",
    "name": "AndAccordionContent",
    "description": "Collapsible panel revealed when its sibling `and-accordion-trigger` is expanded. Must be a child of `and-accordion-item`. Renders `role=\"region\"` and `aria-hidden` from the shared headless logic, and is hidden via the `hidden` attribute (not just CSS) when collapsed.",
    "parent": "and-accordion",
    "attributes": [],
    "events": [],
    "methods": [
      {
        "name": "setItemProps",
        "description": "Receive item properties from parent accordion-item."
      }
    ],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-accordion-item",
    "name": "AndAccordionItem",
    "description": "Wraps one trigger/content pair and bridges it to the parent `and-accordion`'s headless logic. Auto-generates `value` if omitted, so it's safe to skip.",
    "parent": "and-accordion",
    "attributes": [
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Whether this item is disabled (non-interactive, visually dimmed)."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "description": "Unique value identifying this item. Auto-generated if omitted."
      }
    ],
    "events": [],
    "methods": [
      {
        "name": "setAccordionLogic",
        "description": "Called by parent accordion to inject the headless logic."
      }
    ],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-accordion-trigger",
    "name": "AndAccordionTrigger",
    "description": "Clickable header that toggles an `and-accordion-item`. Must be a child of `and-accordion-item`, which injects the shared headless logic via `setItemProps()`. Renders `aria-expanded`/`aria-controls`/`role=\"button\"` from that logic, so screen readers and keyboard users get the same contract as the visual state.",
    "parent": "and-accordion",
    "attributes": [],
    "events": [],
    "methods": [
      {
        "name": "setItemProps",
        "description": "Receive item properties from parent accordion-item."
      }
    ],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-alert",
    "name": "AndAlert",
    "description": "Contextual message banner for feedback, warnings, or errors. Renders with `role=\"alert\"` so assistive tech announces it as soon as it mounts — don't use it for content that appears well before it's relevant, since that triggers an announcement immediately on page load too.",
    "attributes": [
      {
        "name": "dismissible",
        "field": "dismissible",
        "type": "boolean",
        "default": "false",
        "description": "Whether the alert can be dismissed."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"destructive\" | \"info\" | \"success\" | \"warning\"",
        "default": "'default'",
        "description": "Visual variant of the alert."
      }
    ],
    "events": [
      {
        "name": "andDismiss",
        "description": "Emitted when the alert is dismissed.",
        "type": "CustomEvent<void>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-badge",
    "name": "AndBadge",
    "description": "Small label for status, category, or count. Purely presentational — it has no default ARIA role, since forcing `role=\"status\"` on every badge would mislabel static labels (e.g. \"Beta\") as live regions and cause screen readers to announce them as if they update. If a specific badge *does* represent a live status (e.g. an unread count), add `role=\"status\"` on the instance yourself.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"destructive\" | \"outline\" | \"secondary\"",
        "default": "'default'",
        "description": "Visual variant of the badge."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-breadcrumb",
    "name": "AndBreadcrumb",
    "description": "Navigation trail showing the user's location in a hierarchy. Renders a `<nav aria-label>` wrapping an `<ol>` — group `and-breadcrumb-item` children inside it, marking the last one `current`.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes to merge with internal styles."
      },
      {
        "name": "aria-label",
        "field": "navLabel",
        "type": "string",
        "default": "'Breadcrumb'",
        "description": "Accessible label for the breadcrumb navigation."
      },
      {
        "name": "size",
        "field": "size",
        "type": "\"lg\" | \"md\" | \"sm\"",
        "default": "'md'",
        "description": "Size variant for the breadcrumb trail."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-breadcrumb-item",
    "name": "AndBreadcrumbItem",
    "description": "One entry in an `and-breadcrumb` trail. Renders as a link when `href` is set, or a non-interactive `<span>` for the current page. The current item automatically gets `aria-current=\"page\"` — don't set both `current` and `href` expecting a clickable \"you are here\" link, since `current` disables pointer interaction on purpose.",
    "parent": "and-breadcrumb",
    "attributes": [
      {
        "name": "current",
        "field": "current",
        "type": "boolean",
        "default": "false",
        "description": "Marks this item as the current page (adds aria-current)."
      },
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes to merge with internal styles."
      },
      {
        "name": "hide-separator",
        "field": "hideSeparator",
        "type": "boolean",
        "default": "false",
        "description": "Hide the leading separator (typically for the first item)."
      },
      {
        "name": "href",
        "field": "href",
        "type": "string",
        "description": "Optional URL. When set, the item renders as a link."
      },
      {
        "name": "size",
        "field": "size",
        "type": "\"lg\" | \"md\" | \"sm\"",
        "default": "'md'",
        "description": "Size variant — should match the parent breadcrumb size."
      }
    ],
    "events": [
      {
        "name": "andBreadcrumbNavigate",
        "description": "Emitted when a breadcrumb link is activated.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-button",
    "name": "AndButton",
    "description": "Interactive button, or an anchor styled as one when `href` is set. For `size=\"icon\"` (no visible text), pass `aria-label` on the element — it's forwarded to the inner control since the host itself is never left focusable/labelled (an explicit `role`/`tabindex` on the host is moved to the inner button/anchor on load, so there's only one interactive surface for assistive tech to land on).",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes to merge with the internal styles."
      },
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Disables the button when true."
      },
      {
        "name": "href",
        "field": "href",
        "type": "string",
        "default": "''",
        "description": "When set, renders as an anchor (`<a>`) instead of `<button>`."
      },
      {
        "name": "loading",
        "field": "loading",
        "type": "boolean",
        "default": "false",
        "description": "Shows a loading spinner and disables interaction."
      },
      {
        "name": "rel",
        "field": "rel",
        "type": "string",
        "default": "''",
        "description": "Rel attribute for the anchor. Defaults to `noopener noreferrer` when target is `_blank`."
      },
      {
        "name": "size",
        "field": "size",
        "type": "\"default\" | \"icon\" | \"lg\" | \"sm\"",
        "default": "'default'",
        "description": "Size of the button."
      },
      {
        "name": "target",
        "field": "target",
        "type": "string",
        "default": "''",
        "description": "Target for the anchor (e.g. `_blank`). Only used when `href` is set."
      },
      {
        "name": "type",
        "field": "type",
        "type": "\"button\" | \"reset\" | \"submit\"",
        "default": "'button'",
        "description": "HTML button type attribute."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"destructive\" | \"ghost\" | \"link\" | \"outline\" | \"secondary\"",
        "default": "'default'",
        "description": "Visual variant of the button."
      }
    ],
    "events": [
      {
        "name": "andButtonClick",
        "description": "Emitted on button click.",
        "type": "CustomEvent<MouseEvent>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-card",
    "name": "AndCard",
    "description": "Generic content container. Purely presentational — compose it with `and-card-header`, `and-card-title`, `and-card-description`, `and-card-content`, and `and-card-footer` for the standard layout, or use it alone with `padded=\"true\"` for simple content.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "padded",
        "field": "padded",
        "type": "boolean",
        "default": "false",
        "description": "Add built-in padding to the card. Use `true` for simple content without sub-components. Defaults to `false` so sub-components (header/content/footer) manage their own spacing."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"destructive\" | \"elevated\" | \"ghost\" | \"outline\"",
        "default": "'default'",
        "description": "Visual variant of the card."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-card-content",
    "name": "AndCardContent",
    "description": "Main body region of an `and-card`, padded on all sides except the top (so it sits flush under `and-card-header`).",
    "parent": "and-card",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-card-description",
    "name": "AndCardDescription",
    "description": "Secondary, muted text for an `and-card` — typically a one-line summary placed under `and-card-title` inside `and-card-header`.",
    "parent": "and-card",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-card-footer",
    "name": "AndCardFooter",
    "description": "Footer region of an `and-card` — a flex row typically used for actions (buttons) below `and-card-content`.",
    "parent": "and-card",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-card-header",
    "name": "AndCardHeader",
    "description": "Header region of an `and-card` — typically wraps `and-card-title` and `and-card-description`.",
    "parent": "and-card",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-card-title",
    "name": "AndCardTitle",
    "description": "Title text for an `and-card`. Exposed to assistive tech as a real heading (`role=\"heading\"` + `aria-level`) rather than a styled `<div>`, so it shows up in a screen reader's heading navigation. Set `level` to match where the card sits in your document's heading hierarchy — it defaults to `3` (page title → section → card title), but skipping or duplicating levels confuses that navigation, so adjust it per page.",
    "parent": "and-card",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "level",
        "field": "level",
        "type": "1 | 2 | 3 | 4 | 5 | 6",
        "default": "3",
        "description": "Heading level exposed to assistive tech via `aria-level`."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-carousel",
    "name": "AndCarousel",
    "description": "Slideshow of `and-carousel-item` slides with previous/next controls, dot indicators, and optional autoplay. When `autoplay` is on, a pause/play button is shown (required for WCAG 2.2.2 — content that moves for more than 5s must be user-pausable, and pausing only on `mouseenter` leaves keyboard and screen-reader users with no way to stop it). Autoplay also pauses automatically while any control inside the carousel has focus.",
    "attributes": [
      {
        "name": "autoplay",
        "field": "autoplay",
        "type": "boolean",
        "default": "false",
        "description": "Whether the carousel auto-advances. A pause/play control is shown whenever this is true."
      },
      {
        "name": "interval",
        "field": "interval",
        "type": "number",
        "default": "3000",
        "description": "Interval in ms between auto-advances."
      },
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "'Carousel'",
        "description": "ARIA label for the carousel region."
      }
    ],
    "events": [
      {
        "name": "andSlideChange",
        "description": "Emitted when the active slide changes.",
        "type": "CustomEvent<number>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-carousel-item",
    "name": "AndCarouselItem",
    "description": "One slide inside an `and-carousel`. Must be a direct child — the parent counts `and-carousel-item` children on load to size the track.",
    "parent": "and-carousel",
    "attributes": [
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "''",
        "description": "Accessible label announced for this slide (e.g. \"Slide 1 of 3\" context)."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-code",
    "name": "AndCode",
    "description": "Read-only command/code snippet block with a copy-to-clipboard button. Plain text only — it doesn't do syntax highlighting, and `prompt` is just a display hint (no relation to any actual shell or language). The prompt character is hidden by default; opt in with `showPrompt`.",
    "attributes": [
      {
        "name": "copyable",
        "field": "copyable",
        "type": "boolean",
        "default": "true",
        "description": "Whether to show the copy button."
      },
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "height",
        "field": "height",
        "type": "string",
        "default": "'auto'",
        "description": "Fixed height of the block (CSS length)."
      },
      {
        "name": "prompt",
        "field": "prompt",
        "type": "string",
        "default": "'$'",
        "description": "Prompt character shown before each line (e.g. `$`, `>`, `#`). Ignored unless `showPrompt` is `true`."
      },
      {
        "name": "show-prompt",
        "field": "showPrompt",
        "type": "boolean",
        "default": "false",
        "description": "Whether to show the `prompt` character before each line. Off by default — opt in per instance."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "default": "''",
        "description": "Code or command to display."
      }
    ],
    "events": [
      {
        "name": "andCodeCopy",
        "description": "Emitted when the content is copied to the clipboard.",
        "type": "CustomEvent<{ value: string; success: boolean; }>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-context-menu",
    "name": "AndContextMenu",
    "description": "Right-click (or long-press) menu that opens over its `trigger`-slotted content. Supports two usage modes: pass `items` for a built-in, keyboard-navigable list (arrow keys, Home/End, Enter/Space, Escape), or omit `items` and slot your own menu content into the default slot.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes to merge with internal styles."
      },
      {
        "name": "menu-label",
        "field": "menuLabel",
        "type": "string",
        "default": "'Context menu'",
        "description": "Accessible label for the context menu panel."
      },
      {
        "name": "open",
        "field": "open",
        "type": "boolean",
        "default": "false",
        "description": "Whether the context menu is currently open (controlled)."
      }
    ],
    "events": [
      {
        "name": "andContextMenuOpenChange",
        "description": "Emitted when the open state changes.",
        "type": "CustomEvent<boolean>"
      },
      {
        "name": "andContextMenuSelect",
        "description": "Emitted when an item is selected.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-control",
    "name": "AndControl",
    "description": "Generic form-field wrapper: label + your own native/custom control + hint or error message, wired together with real `for`/`id` and `aria-describedby` — for the cases `and-input`/`and-select` don't cover. Unlike those two, this component never renders the control itself; you slot in whatever you need (`<textarea>`, a native `<select>`, a third-party widget, `and-input`, anything), and `and-control` only owns the label/message layout around it. The slotted control keeps its own encapsulation — `and-control` reads the first slotted element, gives it an `id` if it doesn't have one, and points the label's `for` and the message's `aria-describedby` at it. It re-runs whenever the slot's content changes, so this works with content rendered asynchronously by a framework.",
    "attributes": [
      {
        "name": "error",
        "field": "error",
        "type": "string",
        "default": "''",
        "description": "Error message shown below the control instead of `hint`. Also sets `aria-invalid` on the control."
      },
      {
        "name": "hint",
        "field": "hint",
        "type": "string",
        "default": "''",
        "description": "Helper text shown below the control. Hidden while `error` is set."
      },
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "''",
        "description": "Label text for the slotted control."
      },
      {
        "name": "required",
        "field": "required",
        "type": "boolean",
        "default": "false",
        "description": "Shows a required indicator next to the label. Purely visual — set `required` on your own control too."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-drawer",
    "name": "AndDrawer",
    "description": "Off-canvas panel that slides in from an edge of the screen, with a focus trap, Escape-to-close, backdrop click, and focus restoration to whatever was focused before it opened — all handled for you via the shared headless drawer logic.",
    "attributes": [
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "''",
        "description": "Accessible label for the drawer."
      },
      {
        "name": "open",
        "field": "open",
        "type": "boolean",
        "default": "false",
        "description": "Whether the drawer is open."
      },
      {
        "name": "placement",
        "field": "placement",
        "type": "\"bottom\" | \"left\" | \"right\" | \"top\"",
        "default": "'left'",
        "description": "The direction the drawer slides in from."
      },
      {
        "name": "show-close",
        "field": "showClose",
        "type": "boolean",
        "default": "true",
        "description": "Whether to show the default close button in the header."
      }
    ],
    "events": [
      {
        "name": "andDrawerClose",
        "description": "Emitted when the drawer is closed (backdrop click, close button, or Escape).",
        "type": "CustomEvent<void>"
      },
      {
        "name": "andDrawerOpen",
        "description": "Emitted when the drawer is opened.",
        "type": "CustomEvent<void>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-dropdown",
    "name": "AndDropdown",
    "description": "Menu button that opens a list of `items` on click. The trigger gets `aria-haspopup`/`aria-expanded` automatically, and the menu supports arrow keys, Home/End, Enter/Space, and Escape. If you slot a custom `trigger` instead of using the default button, you're responsible for adding those ARIA attributes yourself — they can't be forwarded onto arbitrary slotted content.",
    "attributes": [
      {
        "name": "close-on-select",
        "field": "closeOnSelect",
        "type": "boolean",
        "default": "true",
        "description": "Whether to close the menu after an item is selected."
      },
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "'Options'",
        "description": "Accessible label for the dropdown trigger."
      },
      {
        "name": "placement",
        "field": "placement",
        "type": "\"bottom\" | \"left\" | \"right\" | \"top\"",
        "default": "'bottom'",
        "description": "Preferred placement of the dropdown menu."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"ghost\" | \"outline\" | \"primary\" | \"secondary\"",
        "default": "'default'",
        "description": "Visual variant of the trigger button."
      }
    ],
    "events": [
      {
        "name": "andDropdownOpenChange",
        "description": "Emitted when the dropdown open state changes.",
        "type": "CustomEvent<boolean>"
      },
      {
        "name": "andDropdownSelect",
        "description": "Emitted when an item is selected.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-icon",
    "name": "AndIcon",
    "description": "Renders an SVG icon registered via `registerIcons()`/`registerAllIcons()` from `@andersseen/icon`. Always `aria-hidden=\"true\"` — it's treated as purely decorative, so any accessible name (e.g. \"Close\", \"Copy\") must come from the interactive element it's inside of (`aria-label` on a button, visible text, etc.), never from the icon itself.",
    "attributes": [
      {
        "name": "color",
        "field": "color",
        "type": "string",
        "default": "'currentColor'",
        "description": "The stroke/fill color (defaults to currentColor for theme inheritance)."
      },
      {
        "name": "name",
        "field": "name",
        "type": "string | string & {}",
        "description": "The name of the icon to render (must be registered via `registerIcons()`)."
      },
      {
        "name": "size",
        "field": "size",
        "type": "number | string",
        "default": "24",
        "description": "The size of the icon in pixels."
      },
      {
        "name": "stroke-width",
        "field": "strokeWidth",
        "type": "number | string",
        "default": "2",
        "description": "SVG stroke width."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-input",
    "name": "AndInput",
    "description": "Single-line text input. Since it renders a plain `<input>` with no associated `<label>`, always set `label` (used as `aria-label`) — and when `hasError` is true, also set `describedBy` to point at the id of your visible error message, otherwise screen readers announce the field as invalid without saying why. Renders in light DOM (`scoped` styles, not Shadow DOM) on purpose: the `<input>` this component renders is a real descendant of whatever `<form>` wraps it, so `FormData`, native `required`/`pattern` validation, autofill, and password managers all work without any extra wiring.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "described-by",
        "field": "describedBy",
        "type": "string",
        "default": "''",
        "description": "ID of the element that describes this input (e.g. error message)."
      },
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Disables interaction when true."
      },
      {
        "name": "has-error",
        "field": "hasError",
        "type": "boolean",
        "default": "false",
        "description": "Whether the input is in an error state."
      },
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "''",
        "description": "Accessible label for the input (used when no visible label exists)."
      },
      {
        "name": "name",
        "field": "name",
        "type": "string",
        "default": "''",
        "description": "Name attribute forwarded to the native input — required for it to show up in `FormData`."
      },
      {
        "name": "placeholder",
        "field": "placeholder",
        "type": "string",
        "default": "''",
        "description": "Placeholder text for the input."
      },
      {
        "name": "required",
        "field": "required",
        "type": "boolean",
        "default": "false",
        "description": "Marks the input as required."
      },
      {
        "name": "type",
        "field": "type",
        "type": "\"email\" | \"number\" | \"password\" | \"search\" | \"tel\" | \"text\" | \"url\"",
        "default": "'text'",
        "description": "HTML input type."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "default": "''",
        "description": "Current value of the input."
      }
    ],
    "events": [
      {
        "name": "andInputBlur",
        "description": "Emitted when the input loses focus.",
        "type": "CustomEvent<void>"
      },
      {
        "name": "andInputChange",
        "description": "Emitted when the input value changes.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-menu-item",
    "name": "AndMenuItem",
    "description": "Standalone menu item (`role=\"menuitem\"`), self-contained rather than coordinated by a parent `and-menu-list` — use it when you want to slot individual items directly (e.g. inside `and-dropdown`'s `trigger` slot content) instead of driving `and-menu-list` from an `items` array. Responds to click and Enter/Space.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes to merge with internal styles."
      },
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Disables the menu item when true."
      },
      {
        "name": "intent",
        "field": "intent",
        "type": "\"default\" | \"destructive\"",
        "default": "'default'",
        "description": "Intent variant (default or destructive)."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "description": "Optional value identifier for the item."
      }
    ],
    "events": [
      {
        "name": "andMenuItemSelect",
        "description": "Emitted when the item is selected (clicked or Enter/Space pressed).",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-menu-list",
    "name": "AndMenuList",
    "description": "Data-driven menu (`role=\"menu\"`) that renders `items` as keyboard-navigable `role=\"menuitem\"` entries — arrow keys, Home/End, and typeahead are handled for you. Omit `items` to slot arbitrary content instead (e.g. `and-menu-item` elements), in which case this component only renders the `<ul>` wrapper and doesn't manage focus for you.",
    "attributes": [
      {
        "name": "aria-menu-label",
        "field": "ariaMenuLabel",
        "type": "string",
        "default": "'Menu'",
        "description": "Accessible label for the menu."
      },
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes to merge with internal styles."
      }
    ],
    "events": [
      {
        "name": "andMenuItemSelect",
        "description": "Emitted when an item is selected.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-modal",
    "name": "AndModal",
    "description": "Centered dialog (`role=\"dialog\"`, `aria-modal=\"true\"`) with a focus trap, Escape-to-close, backdrop click, and focus restoration on close. Renders nothing (`<Host />`, no DOM) while closed.",
    "attributes": [
      {
        "name": "animated",
        "field": "animated",
        "type": "boolean",
        "default": "false",
        "description": "Whether to animate the modal entrance and exit."
      },
      {
        "name": "open",
        "field": "open",
        "type": "boolean",
        "default": "false",
        "description": "Whether the modal is open."
      }
    ],
    "events": [
      {
        "name": "andModalClose",
        "description": "Emitted when the modal is closed.",
        "type": "CustomEvent<void>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-navbar",
    "name": "AndNavbar",
    "description": "Responsive top navigation bar. Collapses progressively as viewport shrinks (`full` → `compact` → `minimal` → `mobile`, see `ResponsiveStage`), falling back to an `and-drawer`-based hamburger menu at the `mobile` stage. Active-item tracking supports route, hash, scroll-spy, or fully manual modes via `activeMode`.",
    "attributes": [
      {
        "name": "active-item",
        "field": "activeItem",
        "type": "string",
        "default": "''",
        "description": "The active navigation item ID. Reflects the headless‐core state."
      },
      {
        "name": "active-mode",
        "field": "activeMode",
        "type": "\"auto\" | \"hash\" | \"manual\" | \"route\" | \"scroll\"",
        "default": "'auto'",
        "description": "Strategy used to compute active item. - `auto`: prefers scroll-spy when possible, then route, then hash - `route`: pathname matching (`/docs`, `/demo`) - `hash`: hash matching (`#hero`) - `scroll`: scroll-spy based section tracking - `manual`: external control only (no auto detection)"
      },
      {
        "name": "aria-nav-label",
        "field": "ariaNavLabel",
        "type": "string",
        "default": "'Main navigation'",
        "description": "ARIA label for the navigation"
      },
      {
        "name": "auto-collapse",
        "field": "autoCollapse",
        "type": "boolean",
        "default": "true",
        "description": "When `true`, the navbar automatically detects when the nav items overflow and switches to a smaller responsive stage regardless of breakpoints. Content-aware collapse."
      },
      {
        "name": "compact-breakpoint",
        "field": "compactBreakpoint",
        "type": "number",
        "default": "1024",
        "description": "Breakpoint (px) below which the end section enters compact mode (icon-only, labels hidden). Main nav is still visible."
      },
      {
        "name": "item-variant",
        "field": "itemVariant",
        "type": "\"default\" | \"filled\" | \"underline\"",
        "default": "'default'",
        "description": "Visual style for individual nav links. Controls how each link looks, independent of the navbar container variant. - `default` — subtle rounded pill with hover bg - `underline` — bottom-border indicator on active - `filled` — solid primary bg on active"
      },
      {
        "name": "items",
        "field": "items",
        "type": "NavItem[] | string",
        "default": "[]",
        "description": "Navigation items to display. When provided, the component renders its own items (with full keyboard navigation, scroll-spy, and active‐indicator). When empty, use the `nav` slot for custom content."
      },
      {
        "name": "minimal-breakpoint",
        "field": "minimalBreakpoint",
        "type": "number",
        "default": "768",
        "description": "Breakpoint (px) below which the main (nav links) section is hidden and the navigation moves to the hamburger drawer. Only start + compact end are visible."
      },
      {
        "name": "mobile-breakpoint",
        "field": "mobileBreakpoint",
        "type": "number",
        "default": "640",
        "description": "Breakpoint (px) below which the navbar switches to mobile mode (hamburger menu). Set to `0` to always show desktop, or a high value to always show mobile."
      },
      {
        "name": "position",
        "field": "position",
        "type": "\"fixed\" | \"static\" | \"sticky\"",
        "default": "'static'",
        "description": "Positioning behaviour"
      },
      {
        "name": "route-match-mode",
        "field": "routeMatchMode",
        "type": "\"exact\" | \"prefix\"",
        "default": "'prefix'",
        "description": "Route matching mode used when activeMode resolves through pathname."
      },
      {
        "name": "scroll-spy",
        "field": "scrollSpy",
        "type": "boolean",
        "default": "false",
        "description": "Enable scroll-spy (auto-detect active section by scroll position). Items must have `href` starting with `#`."
      },
      {
        "name": "scroll-spy-offset",
        "field": "scrollSpyOffset",
        "type": "number",
        "default": "100",
        "description": "Scroll-spy offset from the top of viewport (px)."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"filled\" | \"floating\" | \"glass\"",
        "default": "'default'",
        "description": "Visual variant"
      }
    ],
    "events": [
      {
        "name": "andMobileMenuChange",
        "description": "Emitted when mobile menu state changes",
        "type": "CustomEvent<boolean>"
      },
      {
        "name": "andNavItemClick",
        "description": "Emitted when active item changes",
        "type": "CustomEvent<string>"
      },
      {
        "name": "andNavLinkClick",
        "description": "Emitted when a navigation link is clicked",
        "type": "CustomEvent<{ id: string; href: string; }>"
      },
      {
        "name": "andResponsiveStageChange",
        "description": "Emitted when responsive stage changes",
        "type": "CustomEvent<\"compact\" | \"full\" | \"minimal\" | \"mobile\">"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-pagination",
    "name": "AndPagination",
    "description": "Page-number navigation (`nav aria-label=\"Pagination\"`) with previous/next controls. Renders one button per page — for very large `totalPages`, consider paging through results some other way, since this doesn't truncate with an ellipsis.",
    "attributes": [
      {
        "name": "current-page",
        "field": "currentPage",
        "type": "number",
        "default": "1",
        "description": "Current active page (1-based)."
      },
      {
        "name": "total-pages",
        "field": "totalPages",
        "type": "number",
        "default": "1",
        "description": "Total number of pages."
      }
    ],
    "events": [
      {
        "name": "andPageChange",
        "description": "Emitted when the page changes.",
        "type": "CustomEvent<number>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-select",
    "name": "AndSelect",
    "description": "Custom `role=\"combobox\"` select, styleable unlike a native `<select>`. Implements the ARIA combobox pattern: `aria-expanded`, `aria-controls`, `aria-activedescendant` tracks the highlighted option while focus stays on the trigger, and the listbox options get `aria-selected`. A hidden native `<input>` mirrors `value` when `name` is set. Renders in light DOM (`scoped` styles, not Shadow DOM) on purpose: that hidden input is a real descendant of whatever `<form>` wraps this component, so it actually shows up in `FormData` on submit — inside a Shadow DOM it would be invisible to the enclosing form. A `reset` listener on the wrapping `<form>` restores the original default on native `form.reset()` (see `connectedCallback`) — needed because the mirror input's own reset default drifts to whatever was last selected.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "described-by",
        "field": "describedBy",
        "type": "string",
        "default": "''",
        "description": "ID of element describing this field."
      },
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Disables interaction when true."
      },
      {
        "name": "has-error",
        "field": "hasError",
        "type": "boolean",
        "default": "false",
        "description": "Whether the select is in an error state."
      },
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "''",
        "description": "Accessible label for the select."
      },
      {
        "name": "menu-placement",
        "field": "menuPlacement",
        "type": "\"auto\" | \"bottom\" | \"top\"",
        "default": "'auto'",
        "description": "Menu placement strategy."
      },
      {
        "name": "name",
        "field": "name",
        "type": "string",
        "default": "''",
        "description": "Name attribute forwarded to native select."
      },
      {
        "name": "options",
        "field": "options",
        "type": "SelectOption[] | string",
        "default": "[]",
        "description": "Options rendered in the select menu. Can be an array or a JSON string."
      },
      {
        "name": "placeholder",
        "field": "placeholder",
        "type": "string",
        "default": "'Select an option'",
        "description": "Placeholder shown when no value is selected."
      },
      {
        "name": "required",
        "field": "required",
        "type": "boolean",
        "default": "false",
        "description": "Marks the field as required."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "default": "''",
        "description": "Current selected value."
      }
    ],
    "events": [
      {
        "name": "andSelectBlur",
        "description": "Emitted when select loses focus / closes.",
        "type": "CustomEvent<void>"
      },
      {
        "name": "andSelectChange",
        "description": "Emitted when selected value changes.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-sidebar",
    "name": "AndSidebar",
    "description": "Collapsible vertical navigation sidebar (`<aside>`), with `main` and `bottom` item sections and a built-in collapse toggle.",
    "attributes": [
      {
        "name": "active-item",
        "field": "activeItem",
        "type": "string",
        "default": "'home'",
        "description": "The active navigation item ID."
      },
      {
        "name": "aria-nav-label",
        "field": "ariaNavLabel",
        "type": "string",
        "default": "'Sidebar navigation'",
        "description": "ARIA label for the navigation"
      },
      {
        "name": "collapsed",
        "field": "collapsed",
        "type": "boolean",
        "default": "false",
        "description": "Whether the sidebar is collapsed (desktop)."
      },
      {
        "name": "collapsed-width",
        "field": "collapsedWidth",
        "type": "string",
        "default": "'4rem'",
        "description": "Collapsed width of the sidebar."
      },
      {
        "name": "expanded-width",
        "field": "expandedWidth",
        "type": "string",
        "default": "'16rem'",
        "description": "Expanded width of the sidebar."
      },
      {
        "name": "item-variant",
        "field": "itemVariant",
        "type": "\"default\" | \"filled\" | \"underline\"",
        "default": "'default'",
        "description": "Visual style for individual sidebar items."
      },
      {
        "name": "items",
        "field": "items",
        "type": "SidebarItem[] | string",
        "default": "[]",
        "description": "Navigation items to display. Items with `section: 'bottom'` render in the footer area."
      },
      {
        "name": "mobile-breakpoint",
        "field": "mobileBreakpoint",
        "type": "number",
        "default": "768",
        "description": "Breakpoint (px) below which the sidebar auto-collapses on mobile."
      },
      {
        "name": "mobile-collapse",
        "field": "mobileCollapse",
        "type": "boolean",
        "default": "true",
        "description": "Enable auto-collapse on mobile viewports."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"default\" | \"filled\" | \"floating\" | \"glass\"",
        "default": "'default'",
        "description": "Visual variant of the sidebar."
      }
    ],
    "events": [
      {
        "name": "andSidebarItemClick",
        "description": "Emitted when a navigation item is clicked.",
        "type": "CustomEvent<string>"
      },
      {
        "name": "andSidebarToggle",
        "description": "Emitted when the sidebar collapse state changes.",
        "type": "CustomEvent<boolean>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-skeleton",
    "name": "AndSkeleton",
    "description": "Pulsing placeholder shown while content is loading. Announces itself via `aria-busy=\"true\"` and `aria-label=\"Loading\"` — no props needed for accessibility, just size it to roughly match the content it stands in for.",
    "attributes": [
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "height",
        "field": "height",
        "type": "string",
        "default": "'16px'",
        "description": "CSS height (e.g. `16px`, `1rem`)."
      },
      {
        "name": "variant",
        "field": "variant",
        "type": "\"circle\" | \"default\" | \"text\"",
        "default": "'default'",
        "description": "Visual shape of the skeleton."
      },
      {
        "name": "width",
        "field": "width",
        "type": "string",
        "default": "'100%'",
        "description": "CSS width (e.g. `100px`, `100%`)."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-switch",
    "name": "AndSwitch",
    "description": "Boolean on/off toggle. Since it renders a plain `<input type=\"checkbox\" role=\"switch\">` with no associated `<label>`, always set `label` (used as `aria-label`). Renders in light DOM (`scoped` styles, not Shadow DOM) on purpose: the checkbox this component renders is a real descendant of whatever `<form>` wraps it, so `FormData`, native `required` validation, and `<fieldset disabled>` all work without any extra wiring — the visible track/thumb are styled purely off the checkbox's own `:checked`/`:disabled` state via Tailwind `peer-*` variants (see and-switch-variants.ts), and wrapping everything in a `<label>` gives click-to-toggle for free. A `reset` listener on the wrapping `<form>` restores the original default on native `form.reset()` (see `connectedCallback`) — the same gap `and-input` and `and-select` had.",
    "attributes": [
      {
        "name": "checked",
        "field": "checked",
        "type": "boolean",
        "default": "false",
        "description": "Whether the switch is on."
      },
      {
        "name": "class",
        "field": "customClass",
        "type": "string",
        "default": "''",
        "description": "Additional CSS classes from the consumer."
      },
      {
        "name": "described-by",
        "field": "describedBy",
        "type": "string",
        "default": "''",
        "description": "ID of the element that describes this switch (e.g. hint or error message)."
      },
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Disables interaction when true."
      },
      {
        "name": "label",
        "field": "label",
        "type": "string",
        "default": "''",
        "description": "Accessible label for the switch (used when no visible label exists)."
      },
      {
        "name": "name",
        "field": "name",
        "type": "string",
        "default": "''",
        "description": "Name attribute forwarded to the native checkbox — required for it to show up in `FormData`."
      },
      {
        "name": "required",
        "field": "required",
        "type": "boolean",
        "default": "false",
        "description": "Marks the switch as required (must be checked to submit)."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "default": "''",
        "description": "Value submitted in `FormData` when checked. Defaults to the native checkbox default (\"on\") when unset."
      }
    ],
    "events": [
      {
        "name": "andSwitchChange",
        "description": "Emitted when the checked state changes.",
        "type": "CustomEvent<boolean>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-tabs",
    "name": "AndTabs",
    "description": "Tabs root — coordinates `and-tabs-list` > `and-tabs-trigger` and `and-tabs-content` children via shared headless logic, injected into each child automatically. Arrow keys, Home/End, and roving tabindex are handled for you.",
    "attributes": [
      {
        "name": "activation-mode",
        "field": "activationMode",
        "type": "\"automatic\" | \"manual\"",
        "default": "'automatic'",
        "description": "How tabs are activated (on focus or on click)."
      },
      {
        "name": "default-value",
        "field": "defaultValue",
        "type": "string",
        "default": "''",
        "description": "The initial tab value when uncontrolled."
      },
      {
        "name": "orientation",
        "field": "orientation",
        "type": "\"horizontal\" | \"vertical\"",
        "default": "'horizontal'",
        "description": "Orientation of the tab list."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "default": "''",
        "description": "The currently selected tab value."
      }
    ],
    "events": [
      {
        "name": "andTabChange",
        "description": "Emitted when the selected tab changes.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-tabs-content",
    "name": "AndTabsContent",
    "description": "Panel shown when its matching `and-tabs-trigger` (same `value`) is selected. Must be a child of `and-tabs`, which injects the shared headless logic — that's what generates the `id`/`aria-labelledby` pair that ties this panel back to its trigger, so a screen reader announces the panel using the trigger's label.",
    "parent": "and-tabs",
    "attributes": [
      {
        "name": "selected",
        "field": "selected",
        "type": "boolean",
        "default": "false",
        "description": "Whether this content panel is currently selected (set by parent)."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "description": "The value that identifies which tab this content belongs to."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-tabs-list",
    "name": "AndTabsList",
    "description": "`role=\"tablist\"` wrapper for `and-tabs-trigger` children. Purely a layout/labeling wrapper — keyboard navigation lives in the triggers, driven by the headless logic from the `and-tabs` ancestor.",
    "parent": "and-tabs",
    "attributes": [
      {
        "name": "orientation",
        "field": "orientation",
        "type": "\"horizontal\" | \"vertical\"",
        "default": "'horizontal'",
        "description": "Orientation of the tab list."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-tabs-trigger",
    "name": "AndTabsTrigger",
    "description": "Clickable tab header (`role=\"tab\"`). Must be inside `and-tabs-list`, which must itself be inside `and-tabs` — the root injects `tabsLogic` and `selected` into each trigger automatically, which is what drives `aria-selected`, `aria-controls`, and the roving `tabindex`.",
    "parent": "and-tabs",
    "attributes": [
      {
        "name": "disabled",
        "field": "disabled",
        "type": "boolean",
        "default": "false",
        "description": "Whether this tab trigger is disabled."
      },
      {
        "name": "selected",
        "field": "selected",
        "type": "boolean",
        "default": "false",
        "description": "Whether this tab is currently selected (set by parent)."
      },
      {
        "name": "value",
        "field": "value",
        "type": "string",
        "description": "The value that identifies this tab."
      }
    ],
    "events": [
      {
        "name": "andTabTriggerClick",
        "description": "Emitted when this trigger is clicked.",
        "type": "CustomEvent<string>"
      }
    ],
    "methods": [],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-toast",
    "name": "AndToast",
    "description": "Toast notification host and manager. The container is a `role=\"region\"` + `aria-live=\"polite\"` landmark; each toast is `role=\"alert\"` with `aria-live=\"assertive\"` so it's announced immediately. Call `present()` imperatively to show a toast — this component renders no visible content until then.",
    "attributes": [
      {
        "name": "position",
        "field": "position",
        "type": "\"bottom-center\" | \"bottom-left\" | \"bottom-right\" | \"top-center\" | \"top-left\" | \"top-right\"",
        "default": "'bottom-right'",
        "description": "Position of the toast container on screen."
      }
    ],
    "events": [],
    "methods": [
      {
        "name": "present",
        "description": "Present a new toast notification."
      }
    ],
    "slots": [],
    "cssParts": []
  },
  {
    "tag": "and-tooltip",
    "name": "AndTooltip",
    "description": "Wraps its slotted trigger and shows a `role=\"tooltip\"` popup on hover *or* keyboard focus (via `focusin`/`focusout`, not just mouse), per WCAG 1.4.13. Known limitation: `aria-describedby` is applied to the `<and-tooltip>` host element, not to the slotted trigger itself (a custom element can't reach into and mutate arbitrary slotted content). If your trigger is a focusable element like a `<button>`, consider also adding `aria-describedby` on it directly, pointing at this tooltip, for the most reliable screen-reader announcement.",
    "attributes": [
      {
        "name": "close-delay",
        "field": "closeDelay",
        "type": "number",
        "default": "0",
        "description": "Delay in ms before hiding the tooltip."
      },
      {
        "name": "content",
        "field": "content",
        "type": "string",
        "description": "Text content of the tooltip (alternative: use the `content` slot)."
      },
      {
        "name": "open-delay",
        "field": "openDelay",
        "type": "number",
        "default": "0",
        "description": "Delay in ms before showing the tooltip."
      },
      {
        "name": "placement",
        "field": "placement",
        "type": "\"bottom\" | \"left\" | \"right\" | \"top\"",
        "default": "'top'",
        "description": "Preferred placement of the tooltip relative to its trigger."
      }
    ],
    "events": [],
    "methods": [],
    "slots": [],
    "cssParts": []
  }
];
