/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonProps } from "./components/my-button/my-button";
import { DrawerPlacement } from "./components/my-drawer/my-drawer";
import { DropdownItem, DropdownVariant } from "./components/my-dropdown/my-dropdown";
import { IconName } from "./components/my-icon/icons";
import { NavItem } from "./components/my-navbar/my-navbar";
import { SidebarItem } from "./components/my-sidebar/my-sidebar";
import { ToastType } from "./components/my-toast/my-toast";
export { ButtonProps } from "./components/my-button/my-button";
export { DrawerPlacement } from "./components/my-drawer/my-drawer";
export { DropdownItem, DropdownVariant } from "./components/my-dropdown/my-dropdown";
export { IconName } from "./components/my-icon/icons";
export { NavItem } from "./components/my-navbar/my-navbar";
export { SidebarItem } from "./components/my-sidebar/my-sidebar";
export { ToastType } from "./components/my-toast/my-toast";
export namespace Components {
    interface MyAccordion {
        /**
          * @default false
         */
        "collapsible": boolean;
        "defaultValue": string | string[];
        /**
          * @default 'single'
         */
        "type": 'single' | 'multiple';
        "value": string | string[];
    }
    interface MyAccordionContent {
    }
    interface MyAccordionItem {
        /**
          * @default false
         */
        "disabled": boolean;
        "value": string;
    }
    interface MyAccordionTrigger {
    }
    interface MyAlert {
        /**
          * @default 'default'
         */
        "variant": 'default' | 'destructive';
    }
    interface MyBadge {
        /**
          * @default 'default'
         */
        "variant": 'default' | 'secondary' | 'destructive' | 'outline';
    }
    interface MyButton {
        /**
          * Permite pasar clases extra desde fuera
         */
        "customClass": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'default'
         */
        "size": ButtonProps['size'];
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant": ButtonProps['variant'];
    }
    interface MyCard {
        "class": string;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'destructive';
    }
    interface MyCarousel {
        /**
          * @default false
         */
        "autoplay": boolean;
        /**
          * @default 3000
         */
        "interval": number;
    }
    interface MyCarouselItem {
    }
    interface MyDrawer {
        /**
          * Whether the drawer is open.
          * @default false
         */
        "open": boolean;
        /**
          * The direction the drawer slides in from.
          * @default 'left'
         */
        "placement": DrawerPlacement;
    }
    interface MyDropdown {
        /**
          * @default []
         */
        "items": DropdownItem[];
        /**
          * @default 'default'
         */
        "variant": DropdownVariant;
    }
    interface MyIcon {
        /**
          * The color of the icon (default: currentColor)
          * @default 'currentColor'
         */
        "color": string;
        /**
          * The name of the icon to render
         */
        "name": IconName;
        /**
          * The size of the icon (default: 24)
          * @default 24
         */
        "size": string | number;
        /**
          * Stroke width (default: 2)
          * @default 2
         */
        "strokeWidth": string | number;
    }
    interface MyInput {
        "class": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "placeholder": string;
        /**
          * @default 'text'
         */
        "type": string;
        "value": string;
    }
    interface MyModal {
        /**
          * @default false
         */
        "open": boolean;
    }
    interface MyNavbar {
        /**
          * The active navigation item ID
          * @default 'home'
         */
        "activeItem": string;
        /**
          * Navigation items to display
          * @default [     { id: 'home', label: 'Home' },     { id: 'docs', label: 'Docs' },     { id: 'components', label: 'Components' },     { id: 'icons', label: 'Icons' },   ]
         */
        "items": NavItem[];
    }
    interface MyPagination {
        /**
          * current page number
          * @default 1
         */
        "currentPage": number;
        /**
          * total number of pages
          * @default 1
         */
        "totalPages": number;
    }
    interface MySidebar {
        /**
          * The active navigation item ID
          * @default 'home'
         */
        "activeItem": string;
        /**
          * Whether the sidebar is collapsed
          * @default false
         */
        "collapsed": boolean;
        /**
          * Navigation items to display
          * @default [     { id: 'home', label: 'Home' },     { id: 'docs', label: 'Docs' },     { id: 'components', label: 'Components' },   ]
         */
        "items": SidebarItem[];
    }
    interface MyTabs {
        "defaultValue": string;
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        "value": string;
    }
    interface MyTabsContent {
        "value": string;
    }
    interface MyTabsList {
    }
    interface MyTabsTrigger {
        /**
          * @default false
         */
        "disabled": boolean;
        "value": string;
    }
    interface MyToast {
        /**
          * Present a new toast
         */
        "present": (message: string, type?: ToastType, duration?: number) => Promise<void>;
    }
    interface MyTooltip {
        /**
          * @default 0
         */
        "closeDelay": number;
        "content": string;
        /**
          * @default 0
         */
        "openDelay": number;
        /**
          * @default 'top'
         */
        "placement": 'top' | 'right' | 'bottom' | 'left';
    }
}
export interface MyDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyDrawerElement;
}
export interface MyDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyDropdownElement;
}
export interface MyInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyInputElement;
}
export interface MyModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyModalElement;
}
export interface MyNavbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyNavbarElement;
}
export interface MyPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyPaginationElement;
}
export interface MySidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMySidebarElement;
}
export interface MyTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyTabsElement;
}
declare global {
    interface HTMLMyAccordionElement extends Components.MyAccordion, HTMLStencilElement {
    }
    var HTMLMyAccordionElement: {
        prototype: HTMLMyAccordionElement;
        new (): HTMLMyAccordionElement;
    };
    interface HTMLMyAccordionContentElement extends Components.MyAccordionContent, HTMLStencilElement {
    }
    var HTMLMyAccordionContentElement: {
        prototype: HTMLMyAccordionContentElement;
        new (): HTMLMyAccordionContentElement;
    };
    interface HTMLMyAccordionItemElement extends Components.MyAccordionItem, HTMLStencilElement {
    }
    var HTMLMyAccordionItemElement: {
        prototype: HTMLMyAccordionItemElement;
        new (): HTMLMyAccordionItemElement;
    };
    interface HTMLMyAccordionTriggerElement extends Components.MyAccordionTrigger, HTMLStencilElement {
    }
    var HTMLMyAccordionTriggerElement: {
        prototype: HTMLMyAccordionTriggerElement;
        new (): HTMLMyAccordionTriggerElement;
    };
    interface HTMLMyAlertElement extends Components.MyAlert, HTMLStencilElement {
    }
    var HTMLMyAlertElement: {
        prototype: HTMLMyAlertElement;
        new (): HTMLMyAlertElement;
    };
    interface HTMLMyBadgeElement extends Components.MyBadge, HTMLStencilElement {
    }
    var HTMLMyBadgeElement: {
        prototype: HTMLMyBadgeElement;
        new (): HTMLMyBadgeElement;
    };
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyCarouselElement extends Components.MyCarousel, HTMLStencilElement {
    }
    var HTMLMyCarouselElement: {
        prototype: HTMLMyCarouselElement;
        new (): HTMLMyCarouselElement;
    };
    interface HTMLMyCarouselItemElement extends Components.MyCarouselItem, HTMLStencilElement {
    }
    var HTMLMyCarouselItemElement: {
        prototype: HTMLMyCarouselItemElement;
        new (): HTMLMyCarouselItemElement;
    };
    interface HTMLMyDrawerElementEventMap {
        "myClose": void;
    }
    interface HTMLMyDrawerElement extends Components.MyDrawer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyDrawerElementEventMap>(type: K, listener: (this: HTMLMyDrawerElement, ev: MyDrawerCustomEvent<HTMLMyDrawerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyDrawerElementEventMap>(type: K, listener: (this: HTMLMyDrawerElement, ev: MyDrawerCustomEvent<HTMLMyDrawerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyDrawerElement: {
        prototype: HTMLMyDrawerElement;
        new (): HTMLMyDrawerElement;
    };
    interface HTMLMyDropdownElementEventMap {
        "dropdownSelect": string;
    }
    interface HTMLMyDropdownElement extends Components.MyDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyDropdownElementEventMap>(type: K, listener: (this: HTMLMyDropdownElement, ev: MyDropdownCustomEvent<HTMLMyDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyDropdownElementEventMap>(type: K, listener: (this: HTMLMyDropdownElement, ev: MyDropdownCustomEvent<HTMLMyDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyDropdownElement: {
        prototype: HTMLMyDropdownElement;
        new (): HTMLMyDropdownElement;
    };
    interface HTMLMyIconElement extends Components.MyIcon, HTMLStencilElement {
    }
    var HTMLMyIconElement: {
        prototype: HTMLMyIconElement;
        new (): HTMLMyIconElement;
    };
    interface HTMLMyInputElementEventMap {
        "myInput": string;
    }
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyInputElementEventMap>(type: K, listener: (this: HTMLMyInputElement, ev: MyInputCustomEvent<HTMLMyInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyInputElementEventMap>(type: K, listener: (this: HTMLMyInputElement, ev: MyInputCustomEvent<HTMLMyInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyModalElementEventMap {
        "myClose": void;
    }
    interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyModalElementEventMap>(type: K, listener: (this: HTMLMyModalElement, ev: MyModalCustomEvent<HTMLMyModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyModalElementEventMap>(type: K, listener: (this: HTMLMyModalElement, ev: MyModalCustomEvent<HTMLMyModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyModalElement: {
        prototype: HTMLMyModalElement;
        new (): HTMLMyModalElement;
    };
    interface HTMLMyNavbarElementEventMap {
        "navItemClick": string;
    }
    interface HTMLMyNavbarElement extends Components.MyNavbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyNavbarElementEventMap>(type: K, listener: (this: HTMLMyNavbarElement, ev: MyNavbarCustomEvent<HTMLMyNavbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyNavbarElementEventMap>(type: K, listener: (this: HTMLMyNavbarElement, ev: MyNavbarCustomEvent<HTMLMyNavbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyNavbarElement: {
        prototype: HTMLMyNavbarElement;
        new (): HTMLMyNavbarElement;
    };
    interface HTMLMyPaginationElementEventMap {
        "pageChange": number;
    }
    interface HTMLMyPaginationElement extends Components.MyPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyPaginationElementEventMap>(type: K, listener: (this: HTMLMyPaginationElement, ev: MyPaginationCustomEvent<HTMLMyPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyPaginationElementEventMap>(type: K, listener: (this: HTMLMyPaginationElement, ev: MyPaginationCustomEvent<HTMLMyPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyPaginationElement: {
        prototype: HTMLMyPaginationElement;
        new (): HTMLMyPaginationElement;
    };
    interface HTMLMySidebarElementEventMap {
        "sidebarItemClick": string;
        "sidebarToggle": boolean;
    }
    interface HTMLMySidebarElement extends Components.MySidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMySidebarElementEventMap>(type: K, listener: (this: HTMLMySidebarElement, ev: MySidebarCustomEvent<HTMLMySidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMySidebarElementEventMap>(type: K, listener: (this: HTMLMySidebarElement, ev: MySidebarCustomEvent<HTMLMySidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMySidebarElement: {
        prototype: HTMLMySidebarElement;
        new (): HTMLMySidebarElement;
    };
    interface HTMLMyTabsElementEventMap {
        "valueChange": string;
    }
    interface HTMLMyTabsElement extends Components.MyTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyTabsElementEventMap>(type: K, listener: (this: HTMLMyTabsElement, ev: MyTabsCustomEvent<HTMLMyTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyTabsElementEventMap>(type: K, listener: (this: HTMLMyTabsElement, ev: MyTabsCustomEvent<HTMLMyTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyTabsElement: {
        prototype: HTMLMyTabsElement;
        new (): HTMLMyTabsElement;
    };
    interface HTMLMyTabsContentElement extends Components.MyTabsContent, HTMLStencilElement {
    }
    var HTMLMyTabsContentElement: {
        prototype: HTMLMyTabsContentElement;
        new (): HTMLMyTabsContentElement;
    };
    interface HTMLMyTabsListElement extends Components.MyTabsList, HTMLStencilElement {
    }
    var HTMLMyTabsListElement: {
        prototype: HTMLMyTabsListElement;
        new (): HTMLMyTabsListElement;
    };
    interface HTMLMyTabsTriggerElement extends Components.MyTabsTrigger, HTMLStencilElement {
    }
    var HTMLMyTabsTriggerElement: {
        prototype: HTMLMyTabsTriggerElement;
        new (): HTMLMyTabsTriggerElement;
    };
    interface HTMLMyToastElement extends Components.MyToast, HTMLStencilElement {
    }
    var HTMLMyToastElement: {
        prototype: HTMLMyToastElement;
        new (): HTMLMyToastElement;
    };
    interface HTMLMyTooltipElement extends Components.MyTooltip, HTMLStencilElement {
    }
    var HTMLMyTooltipElement: {
        prototype: HTMLMyTooltipElement;
        new (): HTMLMyTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "my-accordion": HTMLMyAccordionElement;
        "my-accordion-content": HTMLMyAccordionContentElement;
        "my-accordion-item": HTMLMyAccordionItemElement;
        "my-accordion-trigger": HTMLMyAccordionTriggerElement;
        "my-alert": HTMLMyAlertElement;
        "my-badge": HTMLMyBadgeElement;
        "my-button": HTMLMyButtonElement;
        "my-card": HTMLMyCardElement;
        "my-carousel": HTMLMyCarouselElement;
        "my-carousel-item": HTMLMyCarouselItemElement;
        "my-drawer": HTMLMyDrawerElement;
        "my-dropdown": HTMLMyDropdownElement;
        "my-icon": HTMLMyIconElement;
        "my-input": HTMLMyInputElement;
        "my-modal": HTMLMyModalElement;
        "my-navbar": HTMLMyNavbarElement;
        "my-pagination": HTMLMyPaginationElement;
        "my-sidebar": HTMLMySidebarElement;
        "my-tabs": HTMLMyTabsElement;
        "my-tabs-content": HTMLMyTabsContentElement;
        "my-tabs-list": HTMLMyTabsListElement;
        "my-tabs-trigger": HTMLMyTabsTriggerElement;
        "my-toast": HTMLMyToastElement;
        "my-tooltip": HTMLMyTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MyAccordion {
        /**
          * @default false
         */
        "collapsible"?: boolean;
        "defaultValue"?: string | string[];
        /**
          * @default 'single'
         */
        "type"?: 'single' | 'multiple';
        "value"?: string | string[];
    }
    interface MyAccordionContent {
    }
    interface MyAccordionItem {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "value"?: string;
    }
    interface MyAccordionTrigger {
    }
    interface MyAlert {
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'destructive';
    }
    interface MyBadge {
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'secondary' | 'destructive' | 'outline';
    }
    interface MyButton {
        /**
          * Permite pasar clases extra desde fuera
         */
        "customClass"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'default'
         */
        "size"?: ButtonProps['size'];
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'default'
         */
        "variant"?: ButtonProps['variant'];
    }
    interface MyCard {
        "class"?: string;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'destructive';
    }
    interface MyCarousel {
        /**
          * @default false
         */
        "autoplay"?: boolean;
        /**
          * @default 3000
         */
        "interval"?: number;
    }
    interface MyCarouselItem {
    }
    interface MyDrawer {
        /**
          * Emitted when the drawer is closed (backdrop click or close button).
         */
        "onMyClose"?: (event: MyDrawerCustomEvent<void>) => void;
        /**
          * Whether the drawer is open.
          * @default false
         */
        "open"?: boolean;
        /**
          * The direction the drawer slides in from.
          * @default 'left'
         */
        "placement"?: DrawerPlacement;
    }
    interface MyDropdown {
        /**
          * @default []
         */
        "items"?: DropdownItem[];
        "onDropdownSelect"?: (event: MyDropdownCustomEvent<string>) => void;
        /**
          * @default 'default'
         */
        "variant"?: DropdownVariant;
    }
    interface MyIcon {
        /**
          * The color of the icon (default: currentColor)
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * The name of the icon to render
         */
        "name"?: IconName;
        /**
          * The size of the icon (default: 24)
          * @default 24
         */
        "size"?: string | number;
        /**
          * Stroke width (default: 2)
          * @default 2
         */
        "strokeWidth"?: string | number;
    }
    interface MyInput {
        "class"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onMyInput"?: (event: MyInputCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default 'text'
         */
        "type"?: string;
        "value"?: string;
    }
    interface MyModal {
        "onMyClose"?: (event: MyModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface MyNavbar {
        /**
          * The active navigation item ID
          * @default 'home'
         */
        "activeItem"?: string;
        /**
          * Navigation items to display
          * @default [     { id: 'home', label: 'Home' },     { id: 'docs', label: 'Docs' },     { id: 'components', label: 'Components' },     { id: 'icons', label: 'Icons' },   ]
         */
        "items"?: NavItem[];
        /**
          * Emitted when a navigation item is clicked
         */
        "onNavItemClick"?: (event: MyNavbarCustomEvent<string>) => void;
    }
    interface MyPagination {
        /**
          * current page number
          * @default 1
         */
        "currentPage"?: number;
        /**
          * Emitted when page changes
         */
        "onPageChange"?: (event: MyPaginationCustomEvent<number>) => void;
        /**
          * total number of pages
          * @default 1
         */
        "totalPages"?: number;
    }
    interface MySidebar {
        /**
          * The active navigation item ID
          * @default 'home'
         */
        "activeItem"?: string;
        /**
          * Whether the sidebar is collapsed
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Navigation items to display
          * @default [     { id: 'home', label: 'Home' },     { id: 'docs', label: 'Docs' },     { id: 'components', label: 'Components' },   ]
         */
        "items"?: SidebarItem[];
        /**
          * Emitted when a navigation item is clicked
         */
        "onSidebarItemClick"?: (event: MySidebarCustomEvent<string>) => void;
        /**
          * Emitted when the sidebar collapse state changes
         */
        "onSidebarToggle"?: (event: MySidebarCustomEvent<boolean>) => void;
    }
    interface MyTabs {
        "defaultValue"?: string;
        "onValueChange"?: (event: MyTabsCustomEvent<string>) => void;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        "value"?: string;
    }
    interface MyTabsContent {
        "value"?: string;
    }
    interface MyTabsList {
    }
    interface MyTabsTrigger {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "value"?: string;
    }
    interface MyToast {
    }
    interface MyTooltip {
        /**
          * @default 0
         */
        "closeDelay"?: number;
        "content"?: string;
        /**
          * @default 0
         */
        "openDelay"?: number;
        /**
          * @default 'top'
         */
        "placement"?: 'top' | 'right' | 'bottom' | 'left';
    }

    interface MyAccordionAttributes {
        "type": 'single' | 'multiple';
        "collapsible": boolean;
        "value": string | string[];
        "defaultValue": string | string[];
    }
    interface MyAccordionItemAttributes {
        "value": string;
        "disabled": boolean;
    }
    interface MyAlertAttributes {
        "variant": 'default' | 'destructive';
    }
    interface MyBadgeAttributes {
        "variant": 'default' | 'secondary' | 'destructive' | 'outline';
    }
    interface MyButtonAttributes {
        "variant": ButtonProps['variant'];
        "size": ButtonProps['size'];
        "type": 'button' | 'submit' | 'reset';
        "disabled": boolean;
        "customClass": string;
    }
    interface MyCardAttributes {
        "variant": 'default' | 'destructive';
        "class": string;
    }
    interface MyCarouselAttributes {
        "autoplay": boolean;
        "interval": number;
    }
    interface MyDrawerAttributes {
        "open": boolean;
        "placement": DrawerPlacement;
    }
    interface MyDropdownAttributes {
        "variant": DropdownVariant;
    }
    interface MyIconAttributes {
        "name": IconName;
        "size": string;
        "color": string;
        "strokeWidth": string;
    }
    interface MyInputAttributes {
        "placeholder": string;
        "value": string;
        "type": string;
        "disabled": boolean;
        "class": string;
    }
    interface MyModalAttributes {
        "open": boolean;
    }
    interface MyNavbarAttributes {
        "activeItem": string;
    }
    interface MyPaginationAttributes {
        "totalPages": number;
        "currentPage": number;
    }
    interface MySidebarAttributes {
        "activeItem": string;
        "collapsed": boolean;
    }
    interface MyTabsAttributes {
        "value": string;
        "defaultValue": string;
        "orientation": 'horizontal' | 'vertical';
    }
    interface MyTabsContentAttributes {
        "value": string;
    }
    interface MyTabsTriggerAttributes {
        "value": string;
        "disabled": boolean;
    }
    interface MyTooltipAttributes {
        "content": string;
        "placement": 'top' | 'right' | 'bottom' | 'left';
        "openDelay": number;
        "closeDelay": number;
    }

    interface IntrinsicElements {
        "my-accordion": Omit<MyAccordion, keyof MyAccordionAttributes> & { [K in keyof MyAccordion & keyof MyAccordionAttributes]?: MyAccordion[K] } & { [K in keyof MyAccordion & keyof MyAccordionAttributes as `attr:${K}`]?: MyAccordionAttributes[K] } & { [K in keyof MyAccordion & keyof MyAccordionAttributes as `prop:${K}`]?: MyAccordion[K] };
        "my-accordion-content": MyAccordionContent;
        "my-accordion-item": Omit<MyAccordionItem, keyof MyAccordionItemAttributes> & { [K in keyof MyAccordionItem & keyof MyAccordionItemAttributes]?: MyAccordionItem[K] } & { [K in keyof MyAccordionItem & keyof MyAccordionItemAttributes as `attr:${K}`]?: MyAccordionItemAttributes[K] } & { [K in keyof MyAccordionItem & keyof MyAccordionItemAttributes as `prop:${K}`]?: MyAccordionItem[K] };
        "my-accordion-trigger": MyAccordionTrigger;
        "my-alert": Omit<MyAlert, keyof MyAlertAttributes> & { [K in keyof MyAlert & keyof MyAlertAttributes]?: MyAlert[K] } & { [K in keyof MyAlert & keyof MyAlertAttributes as `attr:${K}`]?: MyAlertAttributes[K] } & { [K in keyof MyAlert & keyof MyAlertAttributes as `prop:${K}`]?: MyAlert[K] };
        "my-badge": Omit<MyBadge, keyof MyBadgeAttributes> & { [K in keyof MyBadge & keyof MyBadgeAttributes]?: MyBadge[K] } & { [K in keyof MyBadge & keyof MyBadgeAttributes as `attr:${K}`]?: MyBadgeAttributes[K] } & { [K in keyof MyBadge & keyof MyBadgeAttributes as `prop:${K}`]?: MyBadge[K] };
        "my-button": Omit<MyButton, keyof MyButtonAttributes> & { [K in keyof MyButton & keyof MyButtonAttributes]?: MyButton[K] } & { [K in keyof MyButton & keyof MyButtonAttributes as `attr:${K}`]?: MyButtonAttributes[K] } & { [K in keyof MyButton & keyof MyButtonAttributes as `prop:${K}`]?: MyButton[K] };
        "my-card": Omit<MyCard, keyof MyCardAttributes> & { [K in keyof MyCard & keyof MyCardAttributes]?: MyCard[K] } & { [K in keyof MyCard & keyof MyCardAttributes as `attr:${K}`]?: MyCardAttributes[K] } & { [K in keyof MyCard & keyof MyCardAttributes as `prop:${K}`]?: MyCard[K] };
        "my-carousel": Omit<MyCarousel, keyof MyCarouselAttributes> & { [K in keyof MyCarousel & keyof MyCarouselAttributes]?: MyCarousel[K] } & { [K in keyof MyCarousel & keyof MyCarouselAttributes as `attr:${K}`]?: MyCarouselAttributes[K] } & { [K in keyof MyCarousel & keyof MyCarouselAttributes as `prop:${K}`]?: MyCarousel[K] };
        "my-carousel-item": MyCarouselItem;
        "my-drawer": Omit<MyDrawer, keyof MyDrawerAttributes> & { [K in keyof MyDrawer & keyof MyDrawerAttributes]?: MyDrawer[K] } & { [K in keyof MyDrawer & keyof MyDrawerAttributes as `attr:${K}`]?: MyDrawerAttributes[K] } & { [K in keyof MyDrawer & keyof MyDrawerAttributes as `prop:${K}`]?: MyDrawer[K] };
        "my-dropdown": Omit<MyDropdown, keyof MyDropdownAttributes> & { [K in keyof MyDropdown & keyof MyDropdownAttributes]?: MyDropdown[K] } & { [K in keyof MyDropdown & keyof MyDropdownAttributes as `attr:${K}`]?: MyDropdownAttributes[K] } & { [K in keyof MyDropdown & keyof MyDropdownAttributes as `prop:${K}`]?: MyDropdown[K] };
        "my-icon": Omit<MyIcon, keyof MyIconAttributes> & { [K in keyof MyIcon & keyof MyIconAttributes]?: MyIcon[K] } & { [K in keyof MyIcon & keyof MyIconAttributes as `attr:${K}`]?: MyIconAttributes[K] } & { [K in keyof MyIcon & keyof MyIconAttributes as `prop:${K}`]?: MyIcon[K] };
        "my-input": Omit<MyInput, keyof MyInputAttributes> & { [K in keyof MyInput & keyof MyInputAttributes]?: MyInput[K] } & { [K in keyof MyInput & keyof MyInputAttributes as `attr:${K}`]?: MyInputAttributes[K] } & { [K in keyof MyInput & keyof MyInputAttributes as `prop:${K}`]?: MyInput[K] };
        "my-modal": Omit<MyModal, keyof MyModalAttributes> & { [K in keyof MyModal & keyof MyModalAttributes]?: MyModal[K] } & { [K in keyof MyModal & keyof MyModalAttributes as `attr:${K}`]?: MyModalAttributes[K] } & { [K in keyof MyModal & keyof MyModalAttributes as `prop:${K}`]?: MyModal[K] };
        "my-navbar": Omit<MyNavbar, keyof MyNavbarAttributes> & { [K in keyof MyNavbar & keyof MyNavbarAttributes]?: MyNavbar[K] } & { [K in keyof MyNavbar & keyof MyNavbarAttributes as `attr:${K}`]?: MyNavbarAttributes[K] } & { [K in keyof MyNavbar & keyof MyNavbarAttributes as `prop:${K}`]?: MyNavbar[K] };
        "my-pagination": Omit<MyPagination, keyof MyPaginationAttributes> & { [K in keyof MyPagination & keyof MyPaginationAttributes]?: MyPagination[K] } & { [K in keyof MyPagination & keyof MyPaginationAttributes as `attr:${K}`]?: MyPaginationAttributes[K] } & { [K in keyof MyPagination & keyof MyPaginationAttributes as `prop:${K}`]?: MyPagination[K] };
        "my-sidebar": Omit<MySidebar, keyof MySidebarAttributes> & { [K in keyof MySidebar & keyof MySidebarAttributes]?: MySidebar[K] } & { [K in keyof MySidebar & keyof MySidebarAttributes as `attr:${K}`]?: MySidebarAttributes[K] } & { [K in keyof MySidebar & keyof MySidebarAttributes as `prop:${K}`]?: MySidebar[K] };
        "my-tabs": Omit<MyTabs, keyof MyTabsAttributes> & { [K in keyof MyTabs & keyof MyTabsAttributes]?: MyTabs[K] } & { [K in keyof MyTabs & keyof MyTabsAttributes as `attr:${K}`]?: MyTabsAttributes[K] } & { [K in keyof MyTabs & keyof MyTabsAttributes as `prop:${K}`]?: MyTabs[K] };
        "my-tabs-content": Omit<MyTabsContent, keyof MyTabsContentAttributes> & { [K in keyof MyTabsContent & keyof MyTabsContentAttributes]?: MyTabsContent[K] } & { [K in keyof MyTabsContent & keyof MyTabsContentAttributes as `attr:${K}`]?: MyTabsContentAttributes[K] } & { [K in keyof MyTabsContent & keyof MyTabsContentAttributes as `prop:${K}`]?: MyTabsContent[K] };
        "my-tabs-list": MyTabsList;
        "my-tabs-trigger": Omit<MyTabsTrigger, keyof MyTabsTriggerAttributes> & { [K in keyof MyTabsTrigger & keyof MyTabsTriggerAttributes]?: MyTabsTrigger[K] } & { [K in keyof MyTabsTrigger & keyof MyTabsTriggerAttributes as `attr:${K}`]?: MyTabsTriggerAttributes[K] } & { [K in keyof MyTabsTrigger & keyof MyTabsTriggerAttributes as `prop:${K}`]?: MyTabsTrigger[K] };
        "my-toast": MyToast;
        "my-tooltip": Omit<MyTooltip, keyof MyTooltipAttributes> & { [K in keyof MyTooltip & keyof MyTooltipAttributes]?: MyTooltip[K] } & { [K in keyof MyTooltip & keyof MyTooltipAttributes as `attr:${K}`]?: MyTooltipAttributes[K] } & { [K in keyof MyTooltip & keyof MyTooltipAttributes as `prop:${K}`]?: MyTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-accordion": LocalJSX.IntrinsicElements["my-accordion"] & JSXBase.HTMLAttributes<HTMLMyAccordionElement>;
            "my-accordion-content": LocalJSX.IntrinsicElements["my-accordion-content"] & JSXBase.HTMLAttributes<HTMLMyAccordionContentElement>;
            "my-accordion-item": LocalJSX.IntrinsicElements["my-accordion-item"] & JSXBase.HTMLAttributes<HTMLMyAccordionItemElement>;
            "my-accordion-trigger": LocalJSX.IntrinsicElements["my-accordion-trigger"] & JSXBase.HTMLAttributes<HTMLMyAccordionTriggerElement>;
            "my-alert": LocalJSX.IntrinsicElements["my-alert"] & JSXBase.HTMLAttributes<HTMLMyAlertElement>;
            "my-badge": LocalJSX.IntrinsicElements["my-badge"] & JSXBase.HTMLAttributes<HTMLMyBadgeElement>;
            "my-button": LocalJSX.IntrinsicElements["my-button"] & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-card": LocalJSX.IntrinsicElements["my-card"] & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-carousel": LocalJSX.IntrinsicElements["my-carousel"] & JSXBase.HTMLAttributes<HTMLMyCarouselElement>;
            "my-carousel-item": LocalJSX.IntrinsicElements["my-carousel-item"] & JSXBase.HTMLAttributes<HTMLMyCarouselItemElement>;
            "my-drawer": LocalJSX.IntrinsicElements["my-drawer"] & JSXBase.HTMLAttributes<HTMLMyDrawerElement>;
            "my-dropdown": LocalJSX.IntrinsicElements["my-dropdown"] & JSXBase.HTMLAttributes<HTMLMyDropdownElement>;
            "my-icon": LocalJSX.IntrinsicElements["my-icon"] & JSXBase.HTMLAttributes<HTMLMyIconElement>;
            "my-input": LocalJSX.IntrinsicElements["my-input"] & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-modal": LocalJSX.IntrinsicElements["my-modal"] & JSXBase.HTMLAttributes<HTMLMyModalElement>;
            "my-navbar": LocalJSX.IntrinsicElements["my-navbar"] & JSXBase.HTMLAttributes<HTMLMyNavbarElement>;
            "my-pagination": LocalJSX.IntrinsicElements["my-pagination"] & JSXBase.HTMLAttributes<HTMLMyPaginationElement>;
            "my-sidebar": LocalJSX.IntrinsicElements["my-sidebar"] & JSXBase.HTMLAttributes<HTMLMySidebarElement>;
            "my-tabs": LocalJSX.IntrinsicElements["my-tabs"] & JSXBase.HTMLAttributes<HTMLMyTabsElement>;
            "my-tabs-content": LocalJSX.IntrinsicElements["my-tabs-content"] & JSXBase.HTMLAttributes<HTMLMyTabsContentElement>;
            "my-tabs-list": LocalJSX.IntrinsicElements["my-tabs-list"] & JSXBase.HTMLAttributes<HTMLMyTabsListElement>;
            "my-tabs-trigger": LocalJSX.IntrinsicElements["my-tabs-trigger"] & JSXBase.HTMLAttributes<HTMLMyTabsTriggerElement>;
            "my-toast": LocalJSX.IntrinsicElements["my-toast"] & JSXBase.HTMLAttributes<HTMLMyToastElement>;
            "my-tooltip": LocalJSX.IntrinsicElements["my-tooltip"] & JSXBase.HTMLAttributes<HTMLMyTooltipElement>;
        }
    }
}
